import type { Metadata } from "next";
import localFont from "next/font/local";
import ".././globals.css";
import LeftSidebar from "@/components/LeftSidebar";
import RightSidebar from "@/components/RightSidebar";

const geistSans = localFont({
  src: ".././fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: ".././fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex justify-between w-full mx-auto bg-black">
          <div className="left-sidebar hidden sm:inline border-r h-screen sticky top-0">
            <LeftSidebar/>
          </div>
          <div className="main w-2xl flex-1">
          {children}
          </div>
          <div className="right-sidebar lg:flex-col p-3 border-l h-screen border-1 hidden lg:flex w-[24rem]">
            <RightSidebar/>
          </div>
        </div>
        
      </body>
    </html>
  );
}
