import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import LeftSidebar from "@/components/LeftSidebar";
import RightSidebar from "@/components/RightSidebar";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "BuzzShow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex w-full mx-auto">
          {/* Left Sidebar */}
          <div className="hidden sm:block w-[18rem] h-screen sticky top-0">
            <LeftSidebar />
          </div>

          {/* Main Content */}
          <div className="flex-1 p-4 overflow-y-auto">
            {children}
          </div>

          {/* Right Sidebar */}
          <div className="hidden lg:block w-[24rem] p-3 border-l border-white/[0.08] h-screen sticky top-0">
            <RightSidebar />
          </div>
        </div>
      </body>
    </html>
  );
}
